export const SIGN_OUT_OPTION = 'SIGN_OUT_OPTION'

export const ASSIGNMENT_TAB = 'ASSIGNMENT_TAB'
export const NOTICES_TAB = 'NOTICES_TAB'
export const ASSISTANCE_TAB = 'ASSISTANCE_TAB'
export const CREATE_ASSIGNMENT = 'CREATE_ASSIGNMENT'
export const EDIT_ASSIGNMENT = 'EDIT_ASSIGNMENT'
export const CREATE_NOTICE = 'CREATE_NOTICE'
export const EDIT_NOTICE = 'EDIT_NOTICE'
export const QUALIFY_ASSIGNMENT = 'QUALIFIED_ASSIGNMENT'
export const EDIT_ASSIGNMENT_SCORE = 'EDIT_ASSIGNMENT_SCORE'
export const QUALIFY_ASSISTANCE = 'QUALIFY_ASSISTANCE'
export const EDIT_ASSISTANCE = 'EDIT_ASSISTANCE'

export const TABS = [
  {
    id: ASSIGNMENT_TAB,
    name: 'Asignaciones'
  },
  {
    id: NOTICES_TAB,
    name: 'Comunicados'
  },
  {
    id: ASSISTANCE_TAB,
    name: 'Asistencias'
  }
]

export const WITHOUT_TABS_BAR = [
  CREATE_ASSIGNMENT,
  EDIT_ASSIGNMENT,
  CREATE_NOTICE,
  QUALIFY_ASSIGNMENT,
  EDIT_ASSIGNMENT_SCORE,
  QUALIFY_ASSISTANCE,
  EDIT_ASSISTANCE
]
